# Generated by Django 5.0 on 2024-08-22 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField()),
                ('summary_month', models.JSONField()),
                ('summary_products', models.JSONField()),
                ('summary_sales', models.JSONField()),
                ('summary_trends', models.JSONField()),
                ('fig_month', models.JSONField()),
                ('fig_products', models.JSONField()),
                ('fig_sales', models.JSONField()),
                ('fig_trends', models.JSONField()),
                ('revenue', models.FloatField()),
                ('best_selling_product', models.CharField(max_length=255)),
                ('max_quantity_sold', models.IntegerField()),
                ('average_sales_per_month', models.FloatField()),
                ('top_month_sales', models.FloatField()),
                ('significant_changes', models.JSONField()),
                ('sales_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.salesdata')),
            ],
        ),
    ]
