# Generated by Django 5.0 on 2024-08-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_salessummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salessummary',
            name='significant_changes',
        ),
    ]
