# Generated by Django 5.0 on 2024-08-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_salessummary_significant_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salessummary',
            name='fig_month',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='fig_products',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='fig_sales',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='fig_trends',
        ),
    ]
