# Generated by Django 5.0 on 2024-08-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_salessummary_fig_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salessummary',
            name='summary_trends',
        ),
    ]
