# Generated by Django 5.1.4 on 2024-12-30 05:01

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_salessummary_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salessummary',
            options={'verbose_name_plural': 'Sales Summaries'},
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='average_sales_per_month',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='max_quantity_sold',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='revenue',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='avg_sales_by_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='best_month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='highest_quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='highest_sale_recorded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='product_sales_x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='product_sales_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=15), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='sales_by_month_x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='sales_by_month_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=15), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='significant_changes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='total_sales_x',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='total_sales_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=15), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='salessummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='best_selling_product',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='sales_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='analysis.salesdata'),
        ),
    ]
