# Generated by Django 5.0 on 2024-12-31 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_salessummary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salessummary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='avg_sales_by_month',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='highest_sale_recorded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salessummary',
            name='total_sales',
            field=models.FloatField(default=0.0),
        ),
    ]
